server:
  port: 4001
  
spring:
  application:
    name: seasy-cloud-userservice
  profiles:
    active:
    - pro
      
eureka:
  instance:
    ## 续约过期的淘汰时间
    lease-expiration-duration-in-seconds: 15
    ## 续约的心跳频率
    lease-renewal-interval-in-seconds: 5
 
logging:
  config: config/logback.xml
  level:
    root: INFO
    org.springframework.boot.autoconfigure: WARN
   
#开启所有的管理端点给Admin Server进行监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: dev
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
    hystrix:
      strategy:
        enabled: true
  zipkin:
    enabled: false
    base-url: http://localhost:9411
  cloud:
    inetutils:
      preferred-networks:
      - 192.168.84
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:123456@${spring.cloud.client.ip-address}:3001/eureka/
  
---
spring:
  profiles: pro
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
    hystrix:
      strategy:
        enabled: true
  zipkin:
    enabled: false
    base-url: http://zipkin:9411
  cloud:
    inetutils:
      #注册时用的IP网段
      preferred-networks:
      - ${PREFERRED_NETWORKS}
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:123456@${EUREKA_SERVER_ADDRESS}:3001/eureka/
      