server:
  port: 4001
  
spring:
  application:
    name: seasy-cloud-userservice
  security:
    user:
      name: ${spring_security_uid:admin}
      password: ${spring_security_pwd:123456}
  profiles:
    active:
    - ${profiles_active:dev}

#apollo
app:
  id: ${spring.application.name}
apollo:
  meta: ${apollo_meta}
  bootstrap:
    enable: true
    namespaces: application
 
logging:
  config: config/logback.xml
  level:
    org.springframework.boot.autoconfigure: WARN
   
#开启所有的管理端点给Admin Server进行监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: dev
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${spring.cloud.client.ip-address}:3001/eureka/
  
---
spring:
  profiles: pro
  cloud:
    inetutils:
      preferred-networks:
      - ${preferred_networks}
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ## 续约过期的淘汰时间
    lease-expiration-duration-in-seconds: 15
    ## 续约的心跳频率
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka_server_address}:3001/eureka/
      