version: "3.7"

services:
  #mysql
  mysql:
    image: 192.168.134.142/common/mysql:5.7.28
    networks:
      - seasy_overlay
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  #apollo-configservice
  apollo-configservice:
    image: 192.168.134.142/seasy/apollo-configservice:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3201:3201"
    depends_on:
      - mysql
    environment:
      - PREFERRED_NETWORKS=10.10.0
    volumes:
      - /opt/logs/apollo/configservice:/opt/logs/apollo/configservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  #apollo-adminservice
  apollo-adminservice:
    image: 192.168.134.142/seasy/apollo-adminservice:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3202:3202"
    depends_on:
      - mysql
      - apollo-configservice
    environment:
      - PREFERRED_NETWORKS=10.10.0
    volumes:
      - /opt/logs/apollo/adminservice:/opt/logs/apollo/adminservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  #apollo-portal
  apollo-portal:
    image: 192.168.134.142/seasy/apollo-portal:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3203:3203"
    depends_on:
      - mysql
      - apollo-configservice
      - apollo-adminservice
    environment:
      - PREFERRED_NETWORKS=10.10.0
    volumes:
      - /opt/logs/apollo/portal:/opt/logs/apollo/portal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
