version: "3.7"

services:
  eureka1:
    image: 192.168.134.142/seasy/seasy-cloud-eureka:0.0.1-SNAPSHOT
    networks:
      seasy_overlay:
        aliases: 
          - eureka
    ports:
      - "3001:3001"
    environment:
      - EUREKA_HOSTNAME=eureka1
      - PREFERRED_NETWORKS=10.10.0
  eureka2:
    image: 192.168.134.142/seasy/seasy-cloud-eureka:0.0.1-SNAPSHOT
    networks:
      seasy_overlay:
        aliases: 
          - eureka
    ports:
      - "3002:3001"
    environment:
      - EUREKA_HOSTNAME=eureka2
      - PREFERRED_NETWORKS=10.10.0
  eureka3:
    image: 192.168.134.142/seasy/seasy-cloud-eureka:0.0.1-SNAPSHOT
    networks:
      seasy_overlay:
        aliases: 
          - eureka
    ports:
      - "3003:3001"
    environment:
      - EUREKA_HOSTNAME=eureka3
      - PREFERRED_NETWORKS=10.10.0
  adminserver:
    image: 192.168.134.142/seasy/seasy-cloud-adminserver:0.0.1-SNAPSHOT
    networks:
      - seasy_overlay
    ports:
      - "3100:3100"
    environment:
      - EUREKA_SERVER_ADDRESS=eureka
      - PREFERRED_NETWORKS=10.10.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == master
    depends_on:
      - eureka1
      - eureka2
      - eureka3
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
