version: "3.7"

services:
  #skywalking-oap服务
  oap:
    image: apache/skywalking-oap-server:6.5.0
    networks:
      - seasy_overlay
    #depends_on:
    #  - es-server
    ports:
      #Http默认端口 12800，gRPC默认端口 11800
      - 11800:11800
      - 12800:12800
    environment:
      #存储类型有：elasticsearch、h2、mysql
      #- SW_STORAGE=elasticsearch
      #- SW_STORAGE_ES_CLUSTER_NODES=es-server:9200
      - TZ=Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  #skywalking-ui服务
  skywalking-ui:
    image: apache/skywalking-ui:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - oap
    ports:
      - 18080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  #zipkin服务
  zipkin:
    image: openzipkin/zipkin:2.19
    networks:
      - seasy_overlay
    #network_mode: host
    ports:
      - 9411:9411
    environment:
      #mem，mysql， elasticsearch
      - STORAGE_TYPE=mem
      - JAVA_OPTS=-Xms256m -Xmx256m -Dlogging.level.zipkin2=DEBUG
      - TZ=Asia/Shanghai
      #MYSQL，需要5.6或者5.7
      #- MYSQL_DB=zipkin
      #- MYSQL_USER=root
      #- MYSQL_PASS=root
      #- MYSQL_HOST=192.168.47.150
      #- MYSQL_TCP_PORT=3306
      #- MYSQL_MAX_CONNECTIONS=100
      #elasticsearch
      #- ES_HOSTS=192.168.113.168:9200
      #RABBIT
      #- RABBIT_ADDRESSES=192.168.47.150:5672
      #- RABBIT_USER=admin
      #- RABBIT_PASSWORD=admin
      #- RABBIT_QUEUE=zipkin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
  