version: "3.7"

services:
  #skywalking-oap服务
  oap:
    image: apache/skywalking-oap-server:6.5.0
    networks:
      - seasy_overlay
    #depends_on:
    #  - es-server
    ports:
      #Http默认端口 12800，gRPC默认端口 11800
      - 11800:11800
      - 12800:12800
    environment:
      #存储类型有：elasticsearch、h2、mysql
      #- SW_STORAGE=elasticsearch
      #- SW_STORAGE_ES_CLUSTER_NODES=es-server:9200
      - TZ=Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  #skywalking-ui服务
  skywalking-ui:
    image: apache/skywalking-ui:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - oap
    ports:
      - 18080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
  