version: "3.7"

services:
  #elasticsearch服务
  esserver:
    image: elasticsearch:6.4.3
    networks:
      - seasy_overlay
    ports:
      #9200为http协议，用于外部通讯
      #9300位tcp协议，集群节点之间通讯
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=es-cluster
      - node.name=es-node1
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - TZ=Asia/Shanghai
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
      - es-logs:/usr/share/elasticsearch/logs:rw
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  #skywalking-oap服务
  oap:
    image: apache/skywalking-oap-server:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - esserver
    ports:
      #Http默认端口 12800，gRPC默认端口 11800
      - 11800:11800
      - 12800:12800
    environment:
      #存储类型有：elasticsearch、h2、mysql
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=esserver:9200
      - TZ=Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  #skywalking-ui服务
  skywalking-ui:
    image: apache/skywalking-ui:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - oap
    ports:
      - 18080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  #zipkin服务
  zipkin:
    image: openzipkin/zipkin:2.19
    networks:
      - seasy_overlay
    #network_mode: host
    ports:
      - 9411:9411
    environment:
      #mem，mysql， elasticsearch
      - STORAGE_TYPE=mem
      - JAVA_OPTS=-Xms256m -Xmx256m -Dlogging.level.zipkin2=DEBUG
      - TZ=Asia/Shanghai
      #MYSQL，需要5.6或者5.7
      #- MYSQL_DB=zipkin
      #- MYSQL_USER=root
      #- MYSQL_PASS=root
      #- MYSQL_HOST=192.168.47.150
      #- MYSQL_TCP_PORT=3306
      #- MYSQL_MAX_CONNECTIONS=100
      #elasticsearch
      #- ES_HOSTS=192.168.113.168:9200
      #RABBIT
      #- RABBIT_ADDRESSES=192.168.47.150:5672
      #- RABBIT_USER=admin
      #- RABBIT_PASSWORD=admin
      #- RABBIT_QUEUE=zipkin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
  
volumes:
  es-data:
    driver: local
  es-logs:
    driver: local