version: "3.7"

services:
  eureka1:
    image: 192.168.134.147/seasy/seasy-cloud-eureka:0.0.1-SNAPSHOT
    networks:
      seasy_overlay:
        aliases: 
          - eureka
    ports:
      - "3001:3001"
    environment:
      - EUREKA_HOSTNAME=eureka1
  eureka2:
    image: 192.168.134.147/seasy/seasy-cloud-eureka:0.0.1-SNAPSHOT
    networks:
      seasy_overlay:
        aliases: 
          - eureka
    ports:
      - "3002:3001"
    environment:
      - EUREKA_HOSTNAME=eureka2
  eureka3:
    image: 192.168.134.147/seasy/seasy-cloud-eureka:0.0.1-SNAPSHOT
    networks:
      seasy_overlay:
        aliases: 
          - eureka
    ports:
      - "3003:3001"
    environment:
      - EUREKA_HOSTNAME=eureka3
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
