version: "3.7"

services:
  #skywalking-oap服务
  oap:
    image: 192.168.134.147/common/apache/skywalking-oap-server:6.5.0
    networks:
      - seasy_overlay
    #depends_on:
    #  - esserver
    ports:
      #Http默认端口 12800，gRPC默认端口 11800
      - 11800:11800
      - 12800:12800
    environment:
      - TZ=Asia/Shanghai
      #存储类型为elasticsearch
      #- SW_STORAGE=elasticsearch
      #- SW_STORAGE_ES_CLUSTER_NODES=esserver:9200
      #存储类型为mysql，需要手工创建数据库
      - SW_STORAGE=mysql
      - SW_STORAGE_MYSQL_QUERY_MAX_SIZE=5000
      #skywalking-apm-6.5.0版本开始用到的配置
      - SW_JDBC_URL=jdbc:mysql://192.168.134.142:3306/skywalking?characterEncoding=utf8&useSSL=false
      - SW_DATA_SOURCE_USER=root
      - SW_DATA_SOURCE_PASSWORD=123456
      - SW_DATA_SOURCE_CACHE_PREP_STMTS=true
      - SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_SIZE=250
      - SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_LIMIT=2048
      - SW_DATA_SOURCE_USE_SERVER_PREP_STMTS=true
    volumes:
      - /opt/mysql-connector-java-5.1.48.jar:/skywalking/oap-libs/mysql-connector-java-5.1.48.jar
      #skywalking-apm-6.4.0及之前的版本用到的配置
      #- /opt/datasource-settings.properties:/skywalking/config/datasource-settings.properties
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  #skywalking-ui服务
  skywalking-ui:
    image: 192.168.134.147/common/apache/skywalking-ui:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - oap
    ports:
      - 18080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
      - TZ=Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
