version: "3.7"

services:
  apollo-adminservice:
    image: 192.168.134.142/seasy/apollo-adminservice:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3202:3202"
    volumes:
      - apollo-adminservice-log:/opt/logs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
  apollo-configservice:
    image: 192.168.134.142/seasy/apollo-configservice:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3201:3201"
    volumes:
      - apollo-configservice-log:/opt/logs
    depends_on:
      - apollo-adminservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
  apollo-portal:
    image: 192.168.134.142/seasy/apollo-portal:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3203:3203"
    volumes:
      - apollo-portal-log:/opt/logs
    depends_on:
      - apollo-adminservice
      - apollo-configservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
volumes:
  apollo-adminservice-log:
  apollo-configservice-log:
  apollo-portal-log:
