version: "3.7"

services:
  apollo-configservice:
    image: 192.168.134.142/seasy/apollo-configservice:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3201:3201"
    environment:
      - DS_URL=jdbc:mysql://192.168.134.142:3306/ApolloConfigDB?characterEncoding=utf8&useSSL=false
      - DS_USERNAME=root
      - DS_PASSWORD=123456
    volumes:
      - apollo-configservice-log:/opt/logs/apollo/configservice
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
volumes:
  apollo-configservice-log:
