version: "3.7"

services:
  apollo-portal:
    image: 192.168.134.142/seasy/apollo-portal:1.5.1
    networks:
      - seasy_overlay
    ports:
      - "3203:3203"
    depends_on:
      - apollo-configservice
      - apollo-adminservice
    volumes:
      - apollo-portal-log:/opt/logs/apollo/portal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
volumes:
  apollo-portal-log:
