version: "3.7"

services:
  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.7.1
    networks:
      - seasy_overlay
    ports:
      - 8858:8858
      - 8719:8719
    environment:
      - JAVA_OPTS=-Xms256m -Xmx256m
      - TZ=Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
