version: "3.7"

services:
  frontweb:
    image: 192.168.134.142/seasy/seasy-cloud-frontweb:0.0.1-SNAPSHOT
    networks:
      - seasy_overlay
    ports:
      - "4002:4002"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
