version: "3.7"

services:
  #elasticsearch服务
  esserver:
    image: 192.168.134.142/common/elasticsearch:6.4.3
    networks:
      - seasy_overlay
    ports:
      #9200为http协议，用于外部通讯
      #9300位tcp协议，集群节点之间通讯
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=es-cluster
      - node.name=es-node1
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - TZ=Asia/Shanghai
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
      - es-logs:/usr/share/elasticsearch/logs:rw
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  #skywalking-oap服务
  oap:
    image: 192.168.134.142/common/apache/skywalking-oap-server:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - esserver
    ports:
      #Http默认端口 12800，gRPC默认端口 11800
      - 11800:11800
      - 12800:12800
    environment:
      #存储类型有：elasticsearch、h2、mysql
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=esserver:9200
      - TZ=Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  #skywalking-ui服务
  skywalking-ui:
    image: 192.168.134.142/common/apache/skywalking-ui:6.5.0
    networks:
      - seasy_overlay
    depends_on:
      - oap
    ports:
      - 18080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
volumes:
  es-data:
    driver: local
  es-logs:
    driver: local