version: "3.7"

services:
  zipkin:
    image: 192.168.134.147/common/openzipkin/zipkin:2.19
    networks:
      - seasy_overlay
    #network_mode: host
    ports:
      - 9411:9411
    environment:
      #mem，mysql， elasticsearch
      - STORAGE_TYPE=mysql
      - JAVA_OPTS=-Xms256m -Xmx256m -Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
      - TZ=Asia/Shanghai
      #MYSQL，需要5.6或者5.7
      - MYSQL_DB=zipkin
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_HOST=192.168.134.142
      - MYSQL_TCP_PORT=3306
      - MYSQL_MAX_CONNECTIONS=100
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  seasy_overlay:
    external: true
    name: seasy_overlay
