server:
  port: 3001
  
spring:
  application:
    name: seasy-cloud-eureka
  security:
    user:
      name: admin
      password: 123456
  profiles:
    active:
    - pro

eureka:
  instance:
    ## 续约过期的淘汰时间
    lease-expiration-duration-in-seconds: 15
    ## 续约的心跳频率
    lease-renewal-interval-in-seconds: 5
  server:
    ## 是否开启自我保护模式
    enable-self-preservation: false
    ## 心跳阈值重新计算的时间间隔
    # renewal-threshold-update-interval-ms: 120000
    ## 清理失效服务的间隔时间
    eviction-interval-timer-in-ms: 5000
    ## 是否启用只读响应缓存
    use-read-only-response-cache: false
    ## ReadWriteCacheMap的过期时间
    response-cache-auto-expiration-in-seconds: 60
    ## 指定每分钟需要收到的续约次数的阈值
    renewal-percent-threshold: 0.49
    
logging:
  config: config/logback.xml
  level:
    root: INFO
    org.springframework.boot.autoconfigure: WARN

---
spring:
  profiles: dev

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123456@${spring.cloud.client.ip-address}:${server.port}/eureka/
    
---
spring:
  profiles: pro

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
    prefer-ip-address: false
    instance-id: ${EUREKA_HOSTNAME}:${server.port}  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@eureka1:3001/eureka/,http://admin:123456@eureka2:3001/eureka/ 