server:
  port: 3100
  
spring:
  application:
    name: seasy-cloud-adminserver
  #登录admin server的用户名和密码
  security:
    user:
      name: cjm
      password: 123
    
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    ## 续约过期的淘汰时间
    lease-expiration-duration-in-seconds: 15
    ## 续约的心跳频率
    lease-renewal-interval-in-seconds: 5
    #健康检查页面的URL路径
    health-check-url-path: /actuator/health
    #注册给eureka时告诉eureka自己的密码
    metadata-map: 
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 5  
    service-url:
      defaultZone: http://admin:123456@${EUREKA_SERVER_ADDRESS}:3001/eureka/
 
logging:
  config: config/logback.xml
  level:
    root: INFO
    org.springframework.boot.autoconfigure: WARN
   
#开启所有的管理端点给Admin Server进行监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
