spring:
  application:
    name: apollo-adminservice
  datasource:
    url: ${apollo_datasource_config_url}
    username: ${apollo_datasource_username}
    password: ${apollo_datasource_password}

ctrip:
  appid: 100003172

server:
  port: 3202

logging:
  file: /opt/logs/apollo-adminservice.log
