spring:
  application:
    name: apollo-adminservice
  profiles:
    active: github

ctrip:
  appid: 100003172
  
server:
  port: 3202
  
logging:
  file: /opt/logs/apollo/adminservice/apollo-adminservice.log
