server:
  port: 4002
  
spring:
  application:
    name: seasy-cloud-frontweb
  cloud:
    inetutils:
      preferred-networks:
      - 10.0.0

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    
    ## 续约过期的淘汰时间
    lease-expiration-duration-in-seconds: 15
    ## 续约的心跳频率
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://admin:123456@${EUREKA_SERVER_ADDRESS}:3001/eureka/

#Feign的配置信息
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  #服务熔断降级
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  #okhttp:
  #  enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
                
ribbon:
  eureka:
    enabled: true
  #connectTimeout: 10000
  #readTimeout: 10000
  #maxAutoRetries: 0
  #负载均衡
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#seasy-cloud-userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    
logging:
  config: config/logback.xml
  level:
    root: INFO
    org.springframework.boot.autoconfigure: WARN
    com.seasy.cloud.frontweb.feignclient.UserFeignClient: INFO
   
#开启所有的管理端点给Admin Server进行监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
    