spring:
  application:
    name: apollo-configservice
  datasource:
    url: ${apollo_datasource_config_url}
    username: ${apollo_datasource_username}
    password: ${apollo_datasource_password}

ctrip:
  appid: 100003171

server:
  port: 3201

logging:
  file: /opt/logs/apollo-configservice.log
