spring:
  application:
    name: apollo-configservice
  profiles:
    active: github
  cloud:
    inetutils:
      preferred-networks:
      - 10.10.0
      
ctrip:
  appid: 100003171

server:
  port: 3201

logging:
  file: /opt/logs/apollo/configservice/apollo-configservice.log
